### ISSUE TITLE
Undeclared dependency to Java 17

### ISSUE THREAD

**Issue by efasel** [springernature/cf-buildpack-update-action#38]
With https://github.com/springernature/cf-buildpack-update-action/pull/35/files#r1014743168 we need Java 17.

I can make this work by changing 

    tasks.withType<KotlinCompile> {
      kotlinOptions.jvmTarget = "11"
    }

to

    java {
      toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
      }
    }

But I’m not sure about what I’m doing there. :grimacing: 

And this doesn’t force IDEA to use Java 17, but only fixes compiling and testing via gradle. But maybe that’s another problem.

**Comment by dhs3000** [comment]
Compiling and testing via Gradle and also IDEA both does not fail for me with 
```
tasks.withType<KotlinCompile> {
  kotlinOptions.jvmTarget = "11"
}
```

Whereas this fails compiling and testing via Gradle and also IDEA for me
```
val javaVersion = JavaVersion.VERSION_11

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(javaVersion.majorVersion))
    }
}
```
![image](https://user-images.githubusercontent.com/952286/200250194-0a20f6f0-9ddb-4c54-a939-70a6a9faff5f.png)

**Comment by dhs3000** [comment]
@efasel Could you test the above again? Using reloading the Gradle project in IDEA and using "rebuild project"?

**Comment by efasel** [comment]
I removed the `.idea` folder and opened the project again and now it works.

I guess it all comes down to the setting of the "Gradle JVM" here:
![image](https://user-images.githubusercontent.com/5768844/200268300-9bdbdbbd-b339-4f5b-97b1-a26a34fe8590.png)

Before reimporting the project in IDEA it was set to "11" instead of "Project SDK". I don’t know how this "Project SDK" is chosen, but we are not enforcing at least version 17 anywhere, do we?

**Comment by dhs3000** [comment]
> My question is: this now needs a JVM 17. Can we enforce/check this somehow?
I am not sure if I understand this. Where do you want to enforce JVM 17?

The setting mentioned [here](https://github.com/springernature/cf-buildpack-update-action/issues/38#issuecomment-1305190500) compiles the action with 17. The docker container runs / executes the action and uses the Version 17 as well (I needed to updated that, as it could not compile the sources, I am not sure what happens if the compiled code is executed with JVM 11.)


What happens if the code is compiled with this:
```
val javaVersion = JavaVersion.VERSION_17

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(javaVersion.majorVersion))
    }
}
```
Can this be executed on a JVM 11? I thought that the JVM would complain about unsupported version in the classes (I have seen such errors before).

**Comment by efasel** [comment]
> I am not sure if I understand this. Where do you want to enforce JVM 17?

When compiling and testing, via gradlew and via IDEA (which does it via gradle).

This does indeed the trick: [Consuming Toolchains — Toolchains for JVM projects](https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming)

> ## [Consuming Toolchains](https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming)
> 
> A build can globally define what toolchain it targets by stating the Java Language version it needs and optionally the vendor:
> GroovyKotlin
> buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
> 
> ```
> java {
>     toolchain {
>         languageVersion.set(JavaLanguageVersion.of(11))
>     }
> }
> ```
> 
> Executing the build (e.g. using gradle check) will now handle several things for you and others running your build
> * Setup all compile, test and javadoc tasks to use the defined toolchain which may be different than the one Gradle itself uses
> * Gradle detects [locally installed JVMs](https://docs.gradle.org/current/userguide/toolchains.html#sec:auto_detection)
> * Gradle chooses a JRE/JDK matching the requirements of the build (in this case a JVM supporting Java 11)
> * If no matching JVM is found, it will automatically download a matching JDK from [AdoptOpenJDK](https://adoptopenjdk.net/)

Even though if Gradle via IDEA is then configured to use e.g. JVM 11 (see screenshot above), gradle now uses JVM 17:

```
Starting process 'Gradle Test Executor 6'. […] Command: /home/fase01/.gradle/jdks/adoptium-17-x64-hotspot-linux/bin/java […]'

```

```
~/git/cf-buildpack-update-action$ ./gradlew -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + AdoptOpenJDK 1.8.0_292-b10
     | Location:           /home/fase01/.gradle/jdks/jdk8u292-b10
     | Language Version:   8
     | Vendor:             AdoptOpenJDK
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle

 + Eclipse Temurin JDK 17.0.2+8
     | Location:           /home/fase01/.gradle/jdks/adoptium-17-x64-hotspot-linux
     | Language Version:   17
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle

 + Private Build JDK 17.0.4+8-Ubuntu-122.04
     | Location:           /usr/lib/jvm/java-17-openjdk-amd64
     | Language Version:   17
     | Vendor:             Private Build
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM

 + Ubuntu JDK 11.0.16+8-post-Ubuntu-0ubuntu122.04
     | Location:           /usr/lib/jvm/java-11-openjdk-amd64
     | Language Version:   11
     | Vendor:             Ubuntu
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations

 + Invalid toolchains
     + /usr/lib/jvm/openjdk-17
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-17/bin/java''
```
